name: flutterfirebaseddd
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  flutter_bloc: ^4.0.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.5.0
  get_it: ^4.0.2
  injectable: ^0.4.0
  flushbar: ^1.10.4
  uuid: ^2.0.4

dev_dependencies:
  build_runner:
  freezed: ^0.10.9
  lint: ^1.2.0
  injectable_generator: ^0.4.0

flutter:
  uses-material-design: true
